In [3]:
# pip install pandas
import pandas


data = pandas.read_csv('course_feedback.csv')

In [4]:
type(data)

pandas.DataFrame

In [6]:
data.head(5)  # equivalent --> select top 2 * from data

,batch_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date
0,AI Agents and Multi-Agent Systems 02 Jul 2026,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,240,178",5,Great Session!!\n\nGot to learn lot of new top...,"12 Jul, 2026"
1,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"441,782",5,Every concept explain in depth with exapmle an...,"12 Jul, 2026"
2,AI Agents and Multi-Agent Systems 02 Jul 2026,"12 Jul, 2026",Agents Architecture & Design Patterns,"5,938,235",5,Good,"12 Jul, 2026"
3,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,484,534",5,ok,"12 Jul, 2026"
4,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,991,626",5,We have learned different memory techniques an...,"12 Jul, 2026"

In [8]:
# data.tail(5)

In [ ]:
data[['user_id', 'rating']].head(10) # select col1, col2 from data

      user_id  rating
0  11,240,178       5
1     441,782       5
2   5,938,235       5
3  11,484,534       5
4  11,991,626       5
5   1,085,640       5
6  11,115,724       5
7     112,996       5
8  10,860,730       5
9   2,859,890       5

In [ ]:
# type(data[['rating']])

pandas.DataFrame

In [ ]:
# data[['rating']].head(2)

   rating
0       5
1       5

In [17]:
data.columns

Index(['batch_name', 'session_date', 'session_name', 'user_id', 'rating',
       'subjective_feedback', 'feedback_date'],
      dtype='str')

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   batch_name           398 non-null    str
 1   session_date         398 non-null    str
 2   session_name         398 non-null    str
 3   user_id              398 non-null    str
 4   rating               398 non-null    int64
 5   subjective_feedback  195 non-null    str
 6   feedback_date        398 non-null    str
dtypes: int64(1), str(6)
memory usage: 21.9 KB

In [ ]:
# data['batch_name'][0]

'AI Agents and Multi-Agent Systems 02 Jul 2026'

In [ ]:
# type(data['batch_name'])

pandas.Series

In [33]:
data['rating'].head(2)

0    5
1    5
Name: rating, dtype: int64

In [35]:
# read_csv()
# head(). --on dataframe/series
# tail()
# mean()
# info()

data['user_id'].value_counts()

user_id
11,941,662    24
11,115,724    21
11,991,626    20
691,879       19
5,938,235     18
              ..
12,041,147     1
308,539        1
11,967,133     1
10,846,162     1
11,997,566     1
Name: count, Length: 82, dtype: int64

In [ ]:
# selct * from data where user_id = '11,941,662' and rating > 4
cond_1 = data['user_id'] == '11,941,662'
cond_2 = data['rating']>4
cond_3 = data['batch_name'] == 'AI Agents and Multi-Agent Systems 02 Jul 2026'
data[(cond_1 & cond_2 )& cond_3]

,batch_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date
15,AI Agents and Multi-Agent Systems 02 Jul 2026,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,941,662",5,NaN,"12 Jul, 2026"
19,AI Agents and Multi-Agent Systems 02 Jul 2026,"11 Jul, 2026",Memory in AI Agents,"11,941,662",5,NaN,"11 Jul, 2026"
30,AI Agents and Multi-Agent Systems 02 Jul 2026,"5 Jul, 2026",Building Blocks of AI Agents,"11,941,662",5,NaN,"5 Jul, 2026"
44,AI Agents and Multi-Agent Systems 02 Jul 2026,"4 Jul, 2026",Foundation of Agents,"11,941,662",5,NaN,"4 Jul, 2026"

In [42]:
# data['rating'][0]

In [44]:
data['rating']>4

0       True
1       True
2       True
3       True
4       True
       ...
393     True
394    False
395    False
396     True
397     True
Name: rating, Length: 398, dtype: bool

In [51]:
data.groupby('user_id').agg({
    'rating':['mean', 'max', 'min']
})

             rating
               mean max min
user_id
1,085,640  5.000000   5   5
1,541,382  4.000000   4   4
1,595,029  3.500000   4   3
1,884,221  5.000000   5   5
1,983,221  4.000000   4   4
...             ...  ..  ..
691,879    4.789474   5   2
744,819    5.000000   5   5
8,809,463  5.000000   5   5
9,614,498  5.000000   5   5
9,674,827  5.000000   5   5

[82 rows x 3 columns]

In [48]:
data['user_id'].value_counts()

user_id
11,941,662    24
11,115,724    21
11,991,626    20
691,879       19
5,938,235     18
              ..
12,041,147     1
308,539        1
11,967,133     1
10,846,162     1
11,997,566     1
Name: count, Length: 82, dtype: int64

In [56]:
# data

In [54]:
data.groupby(['batch_name', 'user_id']).agg({
    'rating':['mean', 'max', 'min']
}).head(50)

                                                              rating
                                                                mean max min
batch_name                                         user_id
AI Agents and Multi-Agent Systems 02 Jul 2026      1,085,640   5.000   5   5
                                                   10,367,880  5.000   5   5
                                                   10,408,027  5.000   5   5
                                                   11,115,724  5.000   5   5
                                                   11,240,178  5.000   5   5
                                                   11,366,765  1.000   1   1
                                                   11,862,397  5.000   5   5
                                                   11,919,848  4.000   4   4
                                                   11,941,662  5.000   5   5
                                                   12,076,162  5.000   5   5
                                                   2,859,890   5.000   5   5
                                                   5,938,235   5.000   5   5
Basics of NLP and Retrieval-Augmented Generatio... 10,367,880  5.000   5   5
                                                   11,115,724  5.000   5   5
                                                   11,240,178  5.000   5   5
                                                   11,860,828  5.000   5   5
                                                   11,862,397  4.750   5   4
                                                   11,919,848  5.000   5   5
                                                   11,941,662  5.000   5   5
                                                   12,023,611  5.000   5   5
                                                   12,035,591  5.000   5   5
                                                   12,076,162  5.000   5   5
                                                   12,095,157  5.000   5   5
                                                   12,245,496  5.000   5   5
                                                   2,859,890   5.000   5   5
                                                   5,938,235   5.000   5   5
Foundations of Neural Networks and Transformers... 10,298,052  5.000   5   5
                                                   10,454,890  5.000   5   5
                                                   10,539,958  5.000   5   5
                                                   10,675,076  4.750   5   4
                                                   335,221     5.000   5   5
IBM | AI Agents and Multi-Agent Systems 02 Jul ... 10,860,730  5.000   5   5
                                                   10,861,432  3.000   3   3
                                                   11,484,534  5.000   5   5
                                                   11,895,751  5.000   5   5
                                                   11,962,655  5.000   5   5
                                                   11,991,626  5.000   5   5
                                                   112,996     5.000   5   5
                                                   12,022,789  5.000   5   5
                                                   12,023,279  5.000   5   5
                                                   441,782     5.000   5   5
                                                   691,879     5.000   5   5
IBM | Basics of NLP and Retrieval-Augmented Gen... 11,484,534  5.000   5   5
                                                   11,539,113  5.000   5   5
                                                   11,889,794  3.000   3   3
                                                   11,895,751  5.000   5   5
                                                   11,939,556  5.000   5   5
                                                   11,962,655  5.000   5   5
                                                   11,991,626  4.375   5   4
                                                   12,023,279  5.000   5   5

In [57]:
data.head(2)

,batch_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date
0,AI Agents and Multi-Agent Systems 02 Jul 2026,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,240,178",5,Great Session!!\n\nGot to learn lot of new top...,"12 Jul, 2026"
1,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"441,782",5,Every concept explain in depth with exapmle an...,"12 Jul, 2026"

In [65]:
data.rename({
    'batch_name' : 'module_name'},axis=1,inplace=True)

In [ ]:
# data.shape

# rename
# groupby
# agg
# value_counts
# shape
# info
# read_csv()

(398, 7)

In [80]:
data_dict = {
    'user_id':[2,2,2,3,3,3],
    # 'store_name':['A', 'B', 'C', 'D', 'E', 'F'],
    'amount':[231,323,300,400,500,600],
    'qty':[2,1,3,4,5,6],
    'date':['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06']
    
}

df = pandas.DataFrame(data_dict)

In [81]:
df

   user_id  amount  qty        date
0        2     231    2  2023-01-01
1        2     323    1  2023-01-02
2        2     300    3  2023-01-03
3        3     400    4  2023-01-04
4        3     500    5  2023-01-05
5        3     600    6  2023-01-06

In [82]:
df.groupby('user_id').agg({
    'amount':['mean', 'max', 'min']
})

             amount
               mean  max  min
user_id
2        284.666667  323  231
3        500.000000  600  400

In [83]:
df['total_sales'] = df['amount'] * df['qty']
# CELL:
df

   user_id  amount  qty        date  total_sales
0        2     231    2  2023-01-01          462
1        2     323    1  2023-01-02          323
2        2     300    3  2023-01-03          900
3        3     400    4  2023-01-04         1600
4        3     500    5  2023-01-05         2500
5        3     600    6  2023-01-06         3600

In [84]:
df.groupby('user_id').agg({
    'amount':['mean', 'max', 'min'],
    'total_sales':['mean', 'max', 'min']
})

             amount            total_sales
               mean  max  min         mean   max   min
user_id
2        284.666667  323  231   561.666667   900   323
3        500.000000  600  400  2566.666667  3600  1600

In [71]:
# data_size[0]=200

In [64]:
# cleaned_data.head()

In [95]:
def happy_learner(review):
    if isinstance(review, str):
        if 'great' in review.lower():
            return 'Very Happy'
        else:
            return 'SOmething'
    else:
        return 'Some issue with your data'

In [100]:
data['happy_learner'] = data['subjective_feedback'].apply(happy_learner)

In [97]:
output = []

for review in data['subjective_feedback']:
    output.append(happy_learner(review))
    
data['happy_learner'] = output

In [101]:
data.head()

,module_name,session_date,session_name,user_id,rating,subjective_feedback,feedback_date,happy_learner
0,AI Agents and Multi-Agent Systems 02 Jul 2026,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,240,178",5,Great Session!!\n\nGot to learn lot of new top...,"12 Jul, 2026",Very Happy
1,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"441,782",5,Every concept explain in depth with exapmle an...,"12 Jul, 2026",SOmething
2,AI Agents and Multi-Agent Systems 02 Jul 2026,"12 Jul, 2026",Agents Architecture & Design Patterns,"5,938,235",5,Good,"12 Jul, 2026",SOmething
3,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,484,534",5,ok,"12 Jul, 2026",SOmething
4,IBM | AI Agents and Multi-Agent Systems 02 Jul...,"12 Jul, 2026",Agents Architecture & Design Patterns,"11,991,626",5,We have learned different memory techniques an...,"12 Jul, 2026",SOmething

In [93]:
data['subjective_feedback'][1]

'Every concept explain in depth with exapmle and implementations.'

In [102]:
url = (
    "https://raw.githubusercontent.com/pandas-dev"
    "/pandas/main/pandas/tests/io/data/csv/tips.csv"
)

import pandas as pd
tips = pd.read_csv(url)

In [103]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]